Persistant DHT
fr34kcoders/storb pull request #28
Opened 2024-12-26 07:53 UTC by Shr1ftyy

2024-12-26 07:55 UTC, Shr1ftyy commented on storage_subnet/dht/storage.py
> +        self.db_conn = await db.get_db_connection(self.db_dir)
the `db_dir` has to be an argument, as the validator defines where the db is located (see `config.py`).

2025-01-01 06:02 UTC, rishiad commented on db/migrations/20241212075345_validator_db.sql
> +    chunk_length INTEGER,      -- Length of each chunk in bytes
rename to `chunk_size` to maintain consistency with `chunk` table

2025-01-01 06:05 UTC, rishiad commented on db/migrations/20241212075345_validator_db.sql
> +-- Table for mapping infohash to file metadata and chunk IDs
```suggestion
-- Table for mapping infohash to file metadata and chunk hashes
```

2025-01-01 06:06 UTC, rishiad commented on db/migrations/20241212075345_validator_db.sql
> +-- Drop the `miner_stats` table
```suggestion
-- Drop the miner_stats table
```

2025-01-01 06:06 UTC, rishiad commented on db/migrations/20241212075345_validator_db.sql
> +-- Drop the `piece` table
```suggestion
-- Drop the piece table
```

2025-01-01 06:11 UTC, rishiad commented on neurons/validator.py
> +from binascii import unhexlify
unused import. remove it

2025-01-01 06:11 UTC, rishiad commented on neurons/validator.py
>  import aiosqlite
unused import. remove it

2025-01-01 06:11 UTC, rishiad commented on neurons/validator.py
> +from substrateinterface import Keypair
unused import. remove it

2025-01-01 06:16 UTC, rishiad commented on neurons/validator.py
>  async def obtain_metadata_dht(infohash: str, request: Request) -> MetadataResponse:
rename `obtain_metadata_dht` to `obtain_metadata` since this is the only way to get metadata now

2025-01-01 06:22 UTC, rishiad commented on storage_subnet/dht/storage.py
> +from typing import Generator, Union
```suggestion
from typing import Union
```

2025-01-01 06:49 UTC, rishiad requested changes
apply the changes requested

2025-01-03 11:51 UTC, rishiad commented
The history of this branch has diverged too much from incoming fiber rewrite so it will be done from a branch that will be based on the fiber branch.

2025-01-03 11:51 UTC, closed without merging